### ISSUE TITLE
Cookie description in documentation

### ISSUE THREAD

**Issue by r-chris** [maxx-t/nginx-jwt-module#5] opened 2018-09-12 15:53 UTC
I have been trying to use the cookie variant for authentication, but keep getting a JWT parse error. Using the default header option works as expected.

I couldn’t find a good reference how that cookie should look like and tried prefixing the JWT with `Bearer e...` and also tried without, but neither worked. Could you please enlighten me if I need to encode the cookie value somehow?

Thank you!

**Comment by maxx-t** [comment] 2018-09-12 16:05
Well, it can be a cookie as it can be anything:
In the documentation `$cookie_MyCookieName` referes to the nginx's dynamic [cookie vairable](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_cookie_).
So if you want to check a cookie named 'jwt' you'll have to set `auth_jwt` to "$cookie_jwt".
There is some examples in the [test file](https://github.com/maxx-t/nginx-jwt-module/blob/master/test#L117]) where the cookie is named "rampartjwt"

**Comment by maxx-t** [comment] 2018-09-12 20:03
I would look at the underscore.
try to debug it with something like:
```
 location = /api {
        return 200 "cookie is $cookie_lt_jwt";
    }
```

**Comment by r-chris** [comment] 2018-09-12 20:40
You are welcome to try it out here: https://staging-auth0-login.scapp.io
There is a `flask` (`python`) server running underneath `nginx` for the login part, which is roughly based on the `auth0` python example (https://auth0.com/docs/quickstart/webapp/python).

**Comment by maxx-t** [comment] 2018-09-12 20:58
Ok, I found it, the "session" cookie is parsed with the "lt_jwt" one...
I don't know why nginx is behaving like that, I will dig into it.

**Comment by r-chris** [comment] 2018-09-12 21:04
Thanks for looking into this!

**Comment by maxx-t** [comment] 2018-09-12 21:27
That's a strange issue because I cannot reproduce it locally.
I tried `curl <SITE> --cookie 'lt_jwt=eyJ0eX...hn4TY; session=eJzNkMt...rA'` both on your site and localhost, it works on localhost, not on the remote site.
But changing it by `curl <SITE> --cookie 'lt_jwt=eyJ0eX...hn4TY` makes it works...
The problem is not from nginx's way to parse $cookie_name.
Are you manipulating $http_cookie variable at some point ? or $cookie_lt_jwt ?

**Comment by r-chris** [comment] 2018-09-12 21:40
> Are you manipulating $http_cookie variable at some point ? or $cookie_lt_jwt ?

Not intentionally and the python code above appears the only obvious place where any cookie is changes / created. Since I actually won't really need the flask session cookie in the end - I'll see if I can't just disable it.

**Comment by maxx-t** [comment] 2018-09-12 21:57
Maybe there is something checking for the "session" cookie before checking the "lt_jwt" one. Is your server behind a proxy ?

**Comment by r-chris** [comment] 2018-09-12 22:01
Yes, NGINX is being used as a reverse proxy:

    location / {

        proxy_pass         http://127.0.0.1:3000;
        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
        proxy_connect_timeout       300;
        proxy_send_timeout          300;
        proxy_read_timeout          300;
        send_timeout                300;

    }

The flask python server is then run on `127.0.0.1:3000`

**Comment by r-chris** [comment] 2018-09-12 22:03
But since the `401` came from `NGINX` directly, I didn't expect any of the other `locations` to even reach that python code?

**Comment by maxx-t** [comment] 2018-09-12 22:03
Please add `add_header DBG-HTTP-COOKIE $http_cookie;` and `add_header DBG-COOKIE-LT-JWT $cookie_lt_jwt`; in you server configuration to debug it.

**Comment by r-chris** [comment] 2018-09-12 22:14
Ok, I added those as part of the top-level `server` NGINX config. Now the `/application` link works - not sure why, though

**Comment by r-chris** [comment] 2018-09-12 22:44
In the `server` context I had already specified `auth_jwt off;` as the "default". I moved that up one layer and took out the `add_header DBG-...` again. It appears to be working now. So it may indeed be related to #2  - I very much appreciate your help here!

**Comment by maxx-t** [comment] 2018-09-12 22:56
Ok, I will fix #2 tomorrow, it's a simple inheritance issue.

**Comment by maxx-t** [comment] 2018-09-12 23:36
#2 is fixed, closing this issue.

**Comment by r-chris** [comment] 2018-09-13 10:09
Hi @maxx-t it's me again ;) I tested the latest `master` branch and the changes unfortunately didn't solve my problem. In addition, they actually "broke" the previous workaround. Now, putting the `auth_jwt off;` statement in the `http` context , no longer solves this issue for me.

Authentication works when there is **only a single** cookie present. Adding any (random) additional cookie breaks the authentication (as described before).

I added the `header` `Dbg-Http-Cookie` again and it certainly shows all cookies are part of `$http_cookie`. Is there possibly a problem with getting the right cookie down the line?

**Comment by maxx-t** [comment] 2018-09-13 10:16
The important header to set is the a`dd_header DBG-COOKIE-FOO $cookie_your_cookie_name;`.
Also, it sould work without specifying `auth_jwt off;` now.

**Comment by maxx-t** [comment] 2018-09-13 10:30
You can use the "dev" branch, it is fastest to build et in verbose mode:
```
git checkout dev
cd dev
./build 
docker run -p 8000:8000 jwt-nginx-s4
```

then to test other configurations you just have to build with `./build s4` to update the nginx configuration.

--------------------------------

I would suspect the `location = /xxx` in your configuration: if your server is behind a proxy the equal matcher  could not match any example.com//api or  example.com/api/

**Comment by r-chris** [comment] 2018-09-13 11:38
What I can't wrap my head around is if the `location` config was a problem, why would it start to work when I delete any additional cookies?

**Comment by maxx-t** [comment] 2018-09-13 11:50
It may be something due to a problem with [location priority](http://nginx.org/en/docs/http/ngx_http_core_module.html#location), because of your reverse proxy rule, something like:

```
server {
    location / {
       #matches first, see a session cookie, parse it, reject it -> 401
    }
    location = /xxx {

    }
}
```

Also, try to replace, at least for now `location = /xxx` by `location ^~ /xxx`

**Comment by r-chris** [comment] 2018-09-13 12:00
Yes thanks - I did those things. If `location /` really sees a (valid) session cookie, why would it reject it?

I added this debug statement here #9 and looking at the `jwt_data`.

If I have only a single cookie (containing the JWT) `jwt_data` is correct:
`2018/09/13 11:52:07 [debug] 63#63: *5 Found JWT: ey.....`

However, if you add any random additional cookie - it ends up in that `jwt_data` as well like this:
`2018/09/13 11:52:30 [debug] 63#63: *5 Found JWT: ey.....; random=value`

Are you sure there isn't a problem with how the cookie data is being read?

**Comment by maxx-t** [comment] 2018-09-13 12:07
Yes I am: 1) it works with curl, 2) it would imply that nginx cannot parse a cookie correctly, 3) I cannot reproduce.
The problem is either in the way you build your image, either in your nginx configuration.
- Can you reproduce it with `docker run -p 80:80 -v your-nginx-config-dir:/etc/nginx maxxt/nginx-jwt-module:2018-09-13T01-44`
- Can you post your full configuration ?

**Comment by r-chris** [comment] 2018-09-13 12:10
Have you tested with more than one cookie with curl? Because curl and postman doesn't work for me with more than one cookie.

**Comment by r-chris** [comment] 2018-09-13 12:10
There is a comment here:

`// the cookie data is not necessarily null terminated... we need a null terminated character pointer`

https://github.com/tizpuppi/ngx_http_auth_jwt_module/blob/bf8ae5fd4b8e981b7683990378356181dee93842/ngx_http_auth_jwt_module.c#L235

**Comment by maxx-t** [comment] 2018-09-13 12:14
It's not that [pcalloc](https://www.nginx.com/resources/wiki/extending/api/alloc/#ngx-pcalloc ) set all bytes to 0.

**Comment by r-chris** [comment] 2018-09-13 12:15
Still, `curl` doesn't work with more than one cookie

**Comment by r-chris** [comment] 2018-09-13 12:16
I agree that it's most likely my config, though!

**Comment by maxx-t** [comment] 2018-09-13 12:16
Indeed.

**Comment by r-chris** [comment] 2018-09-13 12:56
Let me know if you still need the full config and I'll share it somewhere. Thanks!

**Comment by maxx-t** [comment] 2018-09-13 13:03
Thanks a lot to contributing, I have seen your patch but there is a problem with it: two tests are failing.

**Closed** 2018-09-13 13:53 UTC
Labels: question
